name: Code Quality Workflow


on:
    push:
        branches:
            - main
  
    pull_request:
        branches:
            - main


jobs:
    sonarcloud:
        name: Analyze with SonarCloud
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'temurin'
            
            - name: Cache SonarCloud dependencies
              uses: actions/cache@v2
              with:
                path: ~/.sonar/cache
                key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
            
            - name: Build with Maven
              run: ./mvnw clean install
            
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@v1
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
