name: Test Runner Workflow


on:
    pull_request:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: 17
                distribution: 'zulu' 
            
            - name: Install dependencies
              run: |
                ./mvnw install
            
            - name: Run tests
              run: |
                ./mvnw test